package model;

import java.sql.Date;
import java.sql.Time;

public class BookingModel {
    private int id;              // auto-generated by DB
    private int venueId;
    private String username;
    private Date bookDate;
    private Time startTime;
    private Time endTime;
    private double totalPrice;

    // Getters
    public int getId() { return id; }
    public int getVenueId() { return venueId; }
    public String getUsername() { return username; }
    public Date getBookDate() { return bookDate; }
    public Time getStartTime() { return startTime; }
    public Time getEndTime() { return endTime; }
    public double getTotalPrice() { return totalPrice; }

    // Setters
    public void setId(int id) { this.id = id; }
    public void setVenueId(int venueId) { this.venueId = venueId; }
    public void setUsername(String username) { this.username = username; }
    public void setBookDate(Date bookDate) { this.bookDate = bookDate; }
    public void setStartTime(Time startTime) { this.startTime = startTime; }
    public void setEndTime(Time endTime) { this.endTime = endTime; }
    public void setTotalPrice(double totalPrice) { this.totalPrice = totalPrice; }
}