package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aaisma
 */
public class Navbar extends javax.swing.JFrame {

    /**
     * Creates new form Navbar
     */
    public Navbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnDiscover = new javax.swing.JButton();
        btnFeedback = new javax.swing.JButton();
        contentPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        btnLogin.setBackground(new java.awt.Color(153, 0, 0));
        btnLogin.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(910, 40, 150, 30);

        btnSignup.setBackground(new java.awt.Color(153, 0, 0));
        btnSignup.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("REGISTER");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup);
        btnSignup.setBounds(1100, 40, 150, 30);

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(153, 0, 0));
        btnHome.setText("HOME");
        getContentPane().add(btnHome);
        btnHome.setBounds(210, 40, 110, 30);

        btnAbout.setBackground(new java.awt.Color(204, 204, 204));
        btnAbout.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(153, 0, 0));
        btnAbout.setText("ABOUT US");
        getContentPane().add(btnAbout);
        btnAbout.setBounds(370, 40, 110, 30);

        btnDiscover.setBackground(new java.awt.Color(204, 204, 204));
        btnDiscover.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnDiscover.setForeground(new java.awt.Color(153, 0, 0));
        btnDiscover.setText("DISCOVER");
        getContentPane().add(btnDiscover);
        btnDiscover.setBounds(530, 40, 110, 30);

        btnFeedback.setBackground(new java.awt.Color(204, 204, 204));
        btnFeedback.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnFeedback.setForeground(new java.awt.Color(153, 0, 0));
        btnFeedback.setText("FEEDBACK");
        getContentPane().add(btnFeedback);
        btnFeedback.setBounds(680, 40, 110, 30);

        contentPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-13 002131.png"))); // NOI18N
        contentPanel.setPreferredSize(new java.awt.Dimension(1280, 270));
        getContentPane().add(contentPanel);
        contentPanel.setBounds(0, 0, 1450, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Navbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Navbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Navbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Navbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Navbar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnDiscover;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel contentPanel;
    // End of variables declaration//GEN-END:variables
}
