package view;

import controller.PaymentFormController;
import model.BookingModel;   
import javax.swing.*;

public class PaymentForm extends javax.swing.JFrame {
    private final int bookingId;
    private final double amount;
    private final String username;
    private final PaymentFormController controller;

    public PaymentForm(BookingModel booking) {
        this.bookingId = booking.getId();
        this.amount = booking.getTotalPrice();
        this.username = booking.getUsername();

        this.controller = new PaymentFormController(this);

        initComponents();

        totalAmountLabel.setText("Your total amount is Rs. " + String.format("%.2f", amount));
        statusLabel.setText("Verification result: Pending");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        cashButton = new javax.swing.JButton();
        tokenField = new javax.swing.JTextField();
        khaltiButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(237, 237, 237));

        title.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(153, 0, 0));
        title.setText("PAYEMENT METHOD");

        description.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        description.setText("Perfect! Now choose the payment method you'd like to proceed with!");

        totalAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalAmountLabel.setText("Your total amount is ....");

        cashButton.setBackground(new java.awt.Color(153, 0, 0));
        cashButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        cashButton.setForeground(new java.awt.Color(255, 255, 255));
        cashButton.setText("CASH ON ARRIVAL");
        cashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashButtonActionPerformed(evt);
            }
        });

        khaltiButton.setBackground(new java.awt.Color(153, 0, 0));
        khaltiButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        khaltiButton.setForeground(new java.awt.Color(255, 255, 255));
        khaltiButton.setText("KHALTI TOKEN");
        khaltiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khaltiButtonActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(51, 0, 0));
        statusLabel.setText("status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(description)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(title))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(khaltiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tokenField))))
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalAmountLabel)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(284, 284, 284))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(title)
                .addGap(37, 37, 37)
                .addComponent(description)
                .addGap(39, 39, 39)
                .addComponent(totalAmountLabel)
                .addGap(18, 18, 18)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(cashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(tokenField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(khaltiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(200, 30, 840, 590);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashButtonActionPerformed
        controller.handleCashPayment(bookingId);
        statusLabel.setText("Cash payment processed.");
    }//GEN-LAST:event_cashButtonActionPerformed

    private void khaltiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khaltiButtonActionPerformed
        String token = tokenField.getText();
        controller.handleStripePayment(bookingId, amount, token);
        statusLabel.setText("Stripe payment attempted.");
    }//GEN-LAST:event_khaltiButtonActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashButton;
    private javax.swing.JLabel description;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton khaltiButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel title;
    private javax.swing.JTextField tokenField;
    private javax.swing.JLabel totalAmountLabel;
    // End of variables declaration//GEN-END:variables

    // Inside PaymentForm class
    public JLabel getTotalAmountLabel() { return totalAmountLabel; }
    public JButton getCashButton() { return cashButton; }
    public JButton getKhaltiButton() { return khaltiButton; }
    public JLabel getStatusLabel() { return statusLabel; }
    public JTextField getTokenField() { return tokenField; }
    
}

  
