/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.VenueManagementController;

import javax.swing.*;

/**
 *
 * @author aaisma
 */
public class VenueManagement extends javax.swing.JFrame {
    private final VenueManagementController controller;

   public VenueManagement() {
        initComponents();
        // Use your MySqlConnection class
        controller = new VenueManagementController();
        controller.handleRefresh(venueTable, searchField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        viewBooking = new javax.swing.JLabel();
        venueManagement = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        venueTable = new javax.swing.JTable();
        addressField = new javax.swing.JTextField();
        categoryField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        groundSizeField = new javax.swing.JTextField();
        imagePreviewLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        browseImageButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        imagePathField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        openField = new javax.swing.JTextField();
        closeField = new javax.swing.JTextField();
        searchField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1270, 720));
        setMinimumSize(new java.awt.Dimension(1270, 720));
        setPreferredSize(new java.awt.Dimension(1270, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel19.setText("Dilibazar-01,kathmandu");

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel20.setText("sportease@gmail.com");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("WELCOME ADMIN!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 653, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel20)
                    .addContainerGap(1017, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel1))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel20)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(110, 0, 1170, 30);

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(100, 0, 10, 90);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logosportease.png"))); // NOI18N
        jPanel2.add(logo);
        logo.setBounds(10, 10, 76, 70);

        logoutButton.setBackground(new java.awt.Color(153, 0, 0));
        logoutButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logoutButton);
        logoutButton.setBounds(1090, 50, 160, 30);

        viewBooking.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        viewBooking.setText("View Booking");
        viewBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBookingMouseClicked(evt);
            }
        });
        jPanel2.add(viewBooking);
        viewBooking.setBounds(290, 40, 90, 50);

        venueManagement.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        venueManagement.setForeground(new java.awt.Color(102, 0, 0));
        venueManagement.setText("Venue Management");
        jPanel2.add(venueManagement);
        venueManagement.setBounds(130, 40, 140, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1280, 88);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel6.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel6.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 150, 30));

        venueTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        venueTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        venueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Category", "Open", "Close", "Price", "Ground size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        venueTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venueTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(venueTable);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1202, 290));
        jPanel6.add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 170, 30));
        jPanel6.add(categoryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 140, 30));
        jPanel6.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 140, 30));
        jPanel6.add(groundSizeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, 160, 30));

        imagePreviewLabel.setBackground(new java.awt.Color(255, 255, 255));
        imagePreviewLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        imagePreviewLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        imagePreviewLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        imagePreviewLabel.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel6.add(imagePreviewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, -1, 127));

        addButton.setBackground(new java.awt.Color(255, 204, 204));
        addButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel6.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 212, 35));

        browseImageButton.setBackground(new java.awt.Color(255, 204, 204));
        browseImageButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        browseImageButton.setText("BROWSE");
        browseImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseImageButtonActionPerformed(evt);
            }
        });
        jPanel6.add(browseImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 440, 130, 30));

        updateButton.setBackground(new java.awt.Color(255, 204, 204));
        updateButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel6.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 205, 35));

        refreshButton.setBackground(new java.awt.Color(255, 204, 204));
        refreshButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel6.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 210, 30));

        deleteButton.setBackground(new java.awt.Color(255, 204, 204));
        deleteButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel6.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 210, 32));
        jPanel6.add(imagePathField, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 180, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("Image Path:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));
        jPanel6.add(openField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 140, 30));
        jPanel6.add(closeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 150, 30));

        jPanel1.add(jPanel6);
        jPanel6.setBounds(20, 130, 1240, 490);

        searchField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        jPanel1.add(searchField);
        searchField.setBounds(1000, 100, 255, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Search:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(940, 100, 50, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        controller.handleLogout(this);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void viewBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBookingMouseClicked
        controller.handleViewBooking(this);
        this.dispose();
    }//GEN-LAST:event_viewBookingMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        boolean success = controller.handleAdd(venueTable, nameField, addressField, categoryField,
                openField, closeField,imagePathField, priceField, groundSizeField  
        );
        JOptionPane.showMessageDialog(this, success ? "Venue added!" : "Failed to add venue.");
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        boolean success = controller.handleUpdate(venueTable, nameField, addressField, categoryField,
                openField, closeField,imagePathField, priceField, groundSizeField  
        );
        JOptionPane.showMessageDialog(this, success ? "Venue updated!" : "Failed to update venue.");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void browseImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseImageButtonActionPerformed
        controller.handleBrowseImage(imagePathField, imagePreviewLabel);
    }//GEN-LAST:event_browseImageButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        controller.handleRefresh(venueTable, null);
        JOptionPane.showMessageDialog(this, "Table refreshed!");
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        controller.handleSearch(venueTable, searchField);
    }//GEN-LAST:event_searchFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        boolean success = controller.handleDelete(venueTable, nameField, addressField, categoryField,
                openField, closeField,imagePathField, priceField, groundSizeField  
        );
        JOptionPane.showMessageDialog(this, success ? "Venue deleted!" : "Failed to delete venue.");     
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void venueTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venueTableMouseClicked
        controller.handleLoadImage(imagePathField, imagePreviewLabel);

    // Optionally, also populate the text fields with the selected row’s data
    int selectedRow = venueTable.getSelectedRow();
    if (selectedRow != -1) {
        nameField.setText(venueTable.getValueAt(selectedRow, 1).toString());
        addressField.setText(venueTable.getValueAt(selectedRow, 2).toString());
        categoryField.setText(venueTable.getValueAt(selectedRow, 3).toString());
        closeField.setText(venueTable.getValueAt(selectedRow, 4).toString());
        openField.setText(venueTable.getValueAt(selectedRow, 5).toString());
        priceField.setText(venueTable.getValueAt(selectedRow, 6).toString());
        groundSizeField.setText(venueTable.getValueAt(selectedRow, 7).toString());
        imagePathField.setText(venueTable.getValueAt(selectedRow, 8).toString());
    }
    }//GEN-LAST:event_venueTableMouseClicked



    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenueManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenueManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenueManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenueManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        new VenueManagement().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton browseImageButton;
    private javax.swing.JTextField categoryField;
    private javax.swing.JTextField closeField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField groundSizeField;
    private javax.swing.JTextField imagePathField;
    private javax.swing.JLabel imagePreviewLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField openField;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel venueManagement;
    private javax.swing.JTable venueTable;
    private javax.swing.JLabel viewBooking;
    // End of variables declaration//GEN-END:variables
}
